<?php if (!isset($_SESSION)) {
    session_start();
}
if ($_SESSION['user']['level'] != 1) {
    header("Location: /");
} else {
    ?>
    <ol class="breadcrumb">
        <li><a href="/">Главная</a></li>
        <li><a href="/adminpanel">Админка</a></li>
        <li class="active">Просмотр заказа</li>
    </ol>

    <h2>Просмотр заказа</h2>

    <table class="table">
        <thead>
        <tr>
            <th>#</th>
            <th>Фото</th>
            <th>Название товара</th>
            <th>Модель</th>
            <th>Количество</th>
            <th>Цена за шт</th>
            <th>Цена за коробку</th>
            <th>Итого</th>
        </tr>
        </thead>
        <tbody>
        <?php $tempCost = 0; $url='';?>
        <?php foreach ($this->getDetailOrders as $key => $getDetailOrders) { ?>
            <?php $cost = 1; $url = $getDetailOrders['key']?>
            <tr>
                <td><?= $key + 1 ?></td>
                <td><img src="<?= $getDetailOrders['url']?>"
                         width="150"
                         height="150"></td>
                <td><?= $getDetailOrders['name'] ?></td>
                <td><?= $getDetailOrders['article'] ?></td>
                <td><?= $getDetailOrders['count'] ?></td>
                <td><?= $getDetailOrders['cost'] ?></td>
                <td><?= $getDetailOrders['costall'];?></td>
                <td><?= $cost = $getDetailOrders['costall']*$getDetailOrders['count'];?></td>
            </tr>
        <?php $tempCost+=$cost;?>
        <?php } ?>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>Сумма заказа равна</td>
            <td><span><?=$tempCost?></span> грн</td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td><a href="/adminpanel/cancel?id=<?= $url?>">
                    <button type="submit" class="btn btn-success">Отменить заказ</button>
                </a></td>
            <td>
                <a href="/adminpanel/result?id=<?= $url?>">
                    <button type="submit" class="btn btn-success">Подтвердить заказ</button>
                </a>
            </td>
        </tr>
        </tbody>
    </table>
    <div class="line"></div>
    <div style="text-align: justify">
        <p>"At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti
            atque
            corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in
            culpa
            qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et
            expedita
            distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod
            maxime
            placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam
            et
            aut
            officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non
            recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias
            consequatur aut perferendis doloribus asperiores repellat."
            1914 translation by H. Rackham</p>

        <p>"On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and
            demoralized by
            the
            charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that
            are
            bound
            to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the
            same as
            saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a
            free
            hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like
            best,
            every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the
            claims of
            duty or the obligations of business it will frequently occur that pleasures have to be repudiated and
            annoyances
            accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects
            pleasures
            to secure other greater pleasures, or else he endures pains to avoid worse pains."</p>
    </div>
<?php } ?>