<ol class="breadcrumb">
    <li><a href="#">Home</a></li>
    <li><a href="#">Library</a></li>
    <li class="active">Data</li>
</ol>
<div class="row">
    <?php foreach ($this->getSearchResult as $key => $getAllGoods) { ?>
        <a href="/detail?id=<?= $getAllGoods['id']; ?>">
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <img src="<?= $getAllGoods['url']; ?>"
                         style="width: 208px; height: 208px;">

                    <div class="caption">
                        <h3><?= $getAllGoods['name']; ?></h3>
                        <h5>Артикул: <?= $getAllGoods['article']; ?></h5>

                        <div class="row">
                            <div class="col-xs-6">
                                        <span class="btn btn-danger" style="width: 100%"><?= $getAllGoods['cost']; ?>
                                            грн</span>
                            </div>
                            <div class="col-xs-6">
                                <a href="#" class="btn btn-success" style="color: #FFFFFF; width: 100%"
                                   role="button">Купить</a>
                            </div>
                        </div>
                        <p>Цена коробки: <?= $getAllGoods['costall']; ?> грн. (<?= $getAllGoods['complect']; ?>
                            пар)</p>

                        <p><a href="/products/comparison?id=<?= $getAllGoods['id']; ?>" class="btn btn-default"
                              style="width: 100%"
                              role="button">Добавить к сравнению</a></p>
                    </div>
                </div>
            </div>
        </a>
    <?php } ?>
</div>