<ol class="breadcrumb">
    <li><a href="#">Home</a></li>
    <li><a href="#">Library</a></li>
    <li class="active">Data</li>
</ol>
<div class="content_half float_l">
    <p>Etiam eget leo nisl. Morbi magna enim, lobortis vitae condimentum eu, ultrices a lacus.</p>
</div>
<div class="content_half float_r">
    <h5>Primary Office</h5>
    660-110 Quisque diam at ligula, <br/>
    Etiam dictum lectus quis, 11220<br/>
    Sed mattis mi at sapien<br/><br/>

    Phone: 010-010-6600<br/>
    Email: <a href="mailto:info@yourcompany.com">info@yourcompany.com</a><br/>

    <div class="cleaner h40"></div>

    <h5>Secondary Office</h5>
    120-360 Cras ac nunc laoreet,<br/>
    Nulla vitae leo ac dui, 10680<br/>
    Cras id sem nulla<br/><br/>

    Phone: 030-030-0220<br/>
    Email: <a href="mailto:contact@yourcompany.com">contact@yourcompany.com</a><br/>
    <br/>
</div>

<div class="cleaner h40"></div>

<iframe width="680" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"
        src="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Central+Park,+New+York,+NY,+USA&amp;aq=0&amp;sll=14.093957,1.318359&amp;sspn=69.699334,135.263672&amp;vpsrc=6&amp;ie=UTF8&amp;hq=Central+Park,+New+York,+NY,+USA&amp;ll=40.778265,-73.96988&amp;spn=0.033797,0.06403&amp;t=m&amp;output=embed"></iframe>
