<ol class="breadcrumb">
    <li><a href="#">Home</a></li>
    <li><a href="#">Library</a></li>
    <li class="active">Data</li>
</ol>
<div class="row">
    <div class="col-md-8">
        <h3>Регистрация</h3>
        <h5 class="modal-title" id="myModalLabel">Если Вы уже зарегистрированы, перейдите на страницу <a
                style="color: #000088" href="/login">входа в систему</a>.</h5>
        <p>
        <form class="form-horizontal" role="form" method="post" action="registration">
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-4 control-label">Введите имя</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" name="name" id="inputEmail3" placeholder="Имя" required>
                </div>
            </div>
            <div class="form-group">
                <label for="inputPassword3" class="col-sm-4 control-label">Введите фамилию</label>

                <div class="col-sm-8">
                    <input type="text" class="form-control" name="sirname" id="inputPassword3" placeholder="Фамилия"
                           required>
                </div>
            </div>
            <div class="form-group">
                <label for="inputPassword3" class="col-sm-4 control-label">Придумайте пароль</label>

                <div class="col-sm-8">
                    <input type="password" class="form-control" name="password" id="inputPassword3" placeholder="Пароль"
                           required>
                </div>
            </div>
            <div class="form-group">
                <label for="inputPassword3" class="col-sm-4 control-label">Повторите пароль</label>

                <div class="col-sm-8">
                    <input type="password" class="form-control" name="repeadpass" id="inputPassword3"
                           placeholder="Повторите пароль" required>
                </div>
            </div>
            <div class="form-group">
                <label for="inputPassword3" class="col-sm-4 control-label">Введите рабочий email</label>

                <div class="col-sm-8">
                    <input type="email" class="form-control" name="email" id="inputPassword3" placeholder="Email"
                           required>
                </div>
            </div>
            <div class="form-group">
                <label for="inputPassword3" class="col-sm-4 control-label">Введите мобильный телефон</label>

                <div class="col-sm-8">
                    <input type="text" class="form-control" name="telephone" id="inputPassword3"
                           placeholder="+38 (066) xxx-xx-xx" required>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-4 col-sm-10">
                    <button type="submit" class="btn btn-success">Зарегистрироваться</button>
                </div>
            </div>
        </form>

    </div>
    <div class="col-md-4">
        <h3>Личный кабинет</h3>
    </div>
</div>
